question_data = [{"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
                                      "question": "Rapper Snoop Dogg&#039;s real name is &#039;Cordozar Calvin "
                                                  "Broadus, Jr.&#039;.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
                                      "question": "Soulja Boy&#039;s &#039;Crank That&#039; won a Grammy for Best Rap "
                                                  "Song in 2007.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Geography", "type": "boolean", "difficulty": "easy",
                                      "question": "The Republic of Malta is the smallest microstate worldwide.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                                      "question": "The planet Mars has two moons orbiting it.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Geography", "type": "boolean", "difficulty": "easy",
                                      "question": "San Marino is the only country completely surrounded by another "
                                                  "country.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
                                      "question": "All program codes have to be compiled into an executable file in "
                                                  "order to be run. This file can then be executed on any machine.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Musicals & Theatres", "type": "boolean",
                                      "difficulty": "easy",
                                      "question": "In the play Oedipus Rex, Oedipus kills his father due to jealousy "
                                                  "in loving his mother.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Politics", "type": "boolean", "difficulty": "easy",
                                      "question": "The S in Harry S. Truman stands for &quot;Samuel&quot;.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Geography", "type": "boolean", "difficulty": "medium",
                                      "question": "Israel is 7 hours ahead of New York.", "correct_answer": "True",
                                      "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
                                      "difficulty": "medium",
                                      "question": "The animated film &quot;Spirited Away&quot; won the Academy Award "
                                                  "for Best Animated Feature at the 75th Academy Awards in 2003.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                                      "question": "An eggplant is a vegetable.", "correct_answer": "False",
                                      "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                      "question": "In the original script of &quot;The Matrix&quot;, the machines "
                                                  "used humans as additional computing power instead of batteries.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "Big the Cat is a playable character in &quot;Sonic "
                                                  "Generations&quot;.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean",
                                      "difficulty": "medium",
                                      "question": "In World of Warcraft lore, Thrall is the original wielder of &quot;Doomhammer&quot;.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean",
                                      "difficulty": "medium",
                                      "question": "In &quot;Team Fortress 2&quot;, the &quot;Bill&#039;s Hat&quot; is a reference to the game &quot;Dota 2&quot;.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                      "question": "Shaquille O&#039;Neal appeared in the 1997 film &quot;Space Jam&quot;.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "Deus Ex (2000) does not feature the World Trade Center because it was destroyed by terrorist attacks according to the game&#039;s plot.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
                                      "question": "Sitting for more than three hours a day can cut two years off a person&#039;s life expectancy.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "The ultimate phrase used by Pharah from Overwatch is: &quot;Justice rains from above!&quot;",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean",
                                      "difficulty": "medium",
                                      "question": "The Sniper&#039;s SMG in Team Fortress 2, was originally intended to be the Scout&#039;s primary weapon.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Geography", "type": "boolean", "difficulty": "medium",
                                      "question": "&quot;Mongolia&quot; was a part of the now non-existent U.S.S.R.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                                      "question": "In most programming languages, the operator ++ is equivalent to the statement &quot;+= 1&quot;.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean",
                                      "difficulty": "medium",
                                      "question": "In the game &quot;Subnautica&quot;, a &quot;Cave Crawler&quot; will attack you.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
                                      "question": "The names of Roxas&#039;s Keyblades in Kingdom Hearts are &quot;Oathkeeper&quot; and &quot;Oblivion&quot;.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "question": "Romanian belongs to the Romance language family, shared with French, Spanish, Portuguese and Italian. ",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
                                      "question": "An exothermic reaction is a chemical reaction that releases energy by radiating electricity.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "In Pok&eacute;mon, Bulbasaur is the only starter pokemon that is a Grass\/Poison type.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Film", "type": "boolean", "difficulty": "medium",
                                      "question": "Joan Cusack starred in the 2009 disaster movie, &quot;2012&quot;.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
                                      "question": "Pink Guy&#039;s debut album was &quot;Pink Season&quot;.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
                                      "question": "All of these maps were in &quot;Tom Clancy&#039;s Rainbow Six Siege&quot; on its initial release: House, Clubhouse, Border, Consulate.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean",
                                      "difficulty": "medium",
                                      "question": "In the video game &quot;Transistor&quot;, &quot;Red&quot; is the name of the main character.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "History", "type": "boolean", "difficulty": "hard",
                                      "question": "The USS Missouri (BB-63) last served in the Korean War.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Science: Mathematics", "type": "boolean", "difficulty": "medium",
                                      "question": "A &#039;Millinillion&#039; is a real number.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Television", "type": "boolean",
                                      "difficulty": "medium",
                                      "question": "Klingons once had a period of Democracy in their history, they referred to it as the &quot;Dark Times&quot;.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Science: Mathematics", "type": "boolean", "difficulty": "hard",
                                      "question": "In Topology, the complement of an open set is a closed set.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "hard",
                                      "question": "Stagecoach owned &quot;South West Trains&quot; before losing the rights to FirstGroup and MTR in March of 2017.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Politics", "type": "boolean", "difficulty": "hard",
                                      "question": "George Clinton, Vice President of the United States (1805-1812), is an ancestor of President Bill Clinton.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Music", "type": "boolean", "difficulty": "hard",
                                      "question": "Pete Townshend&#039;s solo album, &quot;White City: A Novel&quot;, is set in the metropolitan area of Chicago.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
                                      "difficulty": "medium",
                                      "question": "In &quot;To Love-Ru: Darkness&quot;, Yami reveals her real name is Eve.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
                                      "difficulty": "hard",
                                      "question": "In the &quot;To Love-Ru&quot; series, Peke is considered a female robot.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "hard",
                                      "question": "Spoon theory is a theory, utilizing &quot;Spoons&quot; as a metaphor for energy they can use in a day.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
                                      "question": "Pneumonoultramicroscopicsilicovolcanoconiosis is a synonym for the disease known as silicosis.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Mythology", "type": "boolean", "difficulty": "easy",
                                      "question": "A wyvern is the same as a dragon.", "correct_answer": "False",
                                      "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                                      "question": "&quot;Sonic the Hedgehog 2&quot; originally was going to have a time travel system.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Video Games", "type": "boolean",
                                      "difficulty": "medium",
                                      "question": "In career mode of &quot;Need for Speed: Underground 2&quot;, the first car the player can drive is the BMW M3 GTR.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
                                      "question": "The 2011 movie &quot;The Adventures of Tintin&quot; was directed by Steven Spielberg.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Cartoon & Animations", "type": "boolean",
                                      "difficulty": "medium",
                                      "question": "Night on Bald Mountain was one of the musical pieces featured in Disney&#039;s 1940&#039;s film Fantasia.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
                                     {"category": "Entertainment: Cartoon & Animations", "type": "boolean",
                                      "difficulty": "medium",
                                      "question": "In &quot;Avatar: The Last Airbender&quot; and &quot;The Legend of Korra&quot;, Lavabending is a specialized bending technique of Firebending.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "History", "type": "boolean", "difficulty": "medium",
                                      "question": "Franz Joseph I was the last emperor of Austria.",
                                      "correct_answer": "False", "incorrect_answers": ["True"]},
                                     {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                                      "question": "The mitochondria is the powerhouse of the cell.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]}]
